apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
stringData:
  CLIENTID: 5j3HQaYDt7EZSrprmM
  CLIENTSECRET: sr46d3bzWUtkUhcLLK9WnDpBjbKnd5fG
  BASE_URL: http://localhost 
