apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
stringData:
  CLIENTID: aYT9hrwWACeUzhDJmc
  CLIENTSECRET: RgWYu5edKmaBJ53KyeCMRrExqVJnLCS7
  BASE_URL: https://devportal.dev.uello.com.br
