apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
data:
  CLIENTID: YVlUOWhyd1dBQ2VVemhESm1j
  CLIENTSECRET: UmdXWXU1ZWRLbWFCSjUzS3llQ01SckV4cVZKbkxDUzc=`
